# Generated by Django 3.1.3 on 2020-11-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_data', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
