# Generated by Django 2.1.7 on 2020-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
