# Generated by Django 2.1.7 on 2020-12-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='img',
        ),
    ]
