version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./OpenEduApi
    ports:
      - "8000:8000"
  nginx-react:
    container_name: ngixreactapp
    build:
      context: ./openedufront
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
volumes:
  static: