// LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// MESSAGE
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// PROFILE
export const FETCH_PROFILE = 'FETCH_PROFILE_INFORMATION'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_ID_AND_STATUS = 'FETCH_PROFILE_ID_AND_STATUS'

// NEWS
export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAIL = "FETCH_NEWS_FAIL";

// SCHEDULE
export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';
export const FETCH_SCHEDULE_FAIL = 'FETCH_SCHEDULE_FAIL';

// LESSONS STUDENT
export const FETCH_LESSONS_STUDENT = 'FETCH_LESSONS_STUDENT';
export const FETCH_LESSONS_STUDENT_SUCCESS = 'FETCH_LESSONS_STUDENT_SUCCESS';
export const FETCH_LESSONS_STUDENT_FAIL = 'FETCH_LESSONS_STUDENT_FAIL';
// BY ID
export const FETCH_LESSONS_STUDENT_BY_ID = "FETCH_LESSONS_STUDENT_BY_ID";
export const FETCH_LESSONS_STUDENT_BY_ID_SUCCESS = "FETCH_LESSONS_STUDENT_BY_ID_SUCCESS";
export const FETCH_LESSONS_STUDENT_BY_ID_FAIL = "FETCH_LESSONS_STUDENT_BY_ID_FAIL";


// LESSONS TEACHER
export const FETCH_LESSONS_TEACHER = "FETCH_LESSONS_TEACHER"
export const FETCH_LESSONS_TEACHER_SUCCESS = "FETCH_LESSONS_TEACHER_SUCCESS"
export const FETCH_LESSONS_TEACHER_FAIL = "FETCH_LESSONS_TEACHER_FAIL"
// BY ID
export const FETCH_LESSONS_TEACHER_BY_ID = "FETCH_LESSONS_TEACHER_BY_ID";
export const FETCH_LESSONS_TEACHER_BY_ID_FAIL = "FETCH_LESSONS_TEACHER_BY_ID_FAIL";
export const FETCH_LESSONS_TEACHER_BY_ID_SUCCESS = "FETCH_LESSONS_TEACHER_BY_ID_SUCCESS"

// DEADLINES
export const FETCH_DEADLINES = "FETCH_DEADLINES";
export const FETCH_DEADLINES_SUCCESS = "FETCH_DEADLINES_SUCCESS";
export const FETCH_DEADLINES_FAIL = "FETCH_DEADLINES_FAIL";
export const ADD_DEADLINES = "ADD_DEADLINES"

// TEACHER GRADES
export const FETCH_TEACHER_GRADES = 'FETCH_TEACHER_GRADES'
export const FETCH_TEACHER_GRADES_SUCCESS = 'FETCH_TEACHER_GRADES_SUCCESS'
export const FETCH_TEACHER_GRADES_FAIL = 'FETCH_TEACHER_GRADES'

// GRADES LESSONS
export const FETCH_GRADES_LESSONS = "FETCH_GRADES_LESSONS"
export const FETCH_GRADES_LESSONS_SUCCESS = "FETCH_GRADES_LESSONS_SUCCESS"
export const FETCH_GRADES_LESSONS_FAIL = "FETCH_GRADES_LESSONS_FAIL"

// TESTS
export const FETCH_TESTS = "FETCH_TESTS"
export const FETCH_TESTS_SUCCESS = "FETCH_TESTS_SUCCESS"
export const FETCH_TESTS_FAIL = "FETCH_TESTS_FAIL"