# Generated by Django 3.1.3 on 2021-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('mini_description', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('img', models.ImageField(blank=True, upload_to='article')),
            ],
        ),
    ]
